# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_polarsr_wrappers", use_symbols = TRUE, package_name = "polarsr")

#' @docType package
#' @usage NULL
#' @useDynLib polarsr, .registration = TRUE
NULL

#' @export
as_int32chunked <- function(x, name) .Call(wrap__as_int32chunked, x, name)

#' @export
as_polar_dataframe <- function(x) .Call(wrap__as_polar_dataframe, x)

PolarsrDataFrame <- new.env(parent = emptyenv())

PolarsrDataFrame$column <- function(name) .Call(wrap__PolarsrDataFrame__column, self, name)

#' @export
`$.PolarsrDataFrame` <- function (self, name) { func <- PolarsrDataFrame[[name]]; environment(func) <- environment(); func }

