# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_polarsr_wrappers", use_symbols = TRUE, package_name = "polarsr")

#' @docType package
#' @usage NULL
#' @useDynLib polarsr, .registration = TRUE
NULL

#' @export
as_in32chunked <- function(x) .Call(wrap__as_in32chunked, x)

